### PR TITLE
AWS Quickstarter: Bump Dependency Versions

### PR DESCRIPTION
**Pull request by tbugfinder**
Update inf-terraform-aws quickstarter bits and pieces:

* update terraform version from 0.14.11 to 1.0.3
* update kitchen-terraform to 5.8.0
* remove Pipfile.lock
* bump hashcorp/random to 3.1.0
* rename inspec test suite from stackdefault to stack
* bump inspec-aws to 1.51.5
* bump inspec to 4.37.30
* bump ruby to 2.7.4
* add cfn-lint to pre-commit-hooks
* set QS version to 4.1 in metadata

Tasks: 
- [ ] Updated documentation in `docs/modules/...` directory
- [ ] Ran tests in `<quickstarter>/testdata` directory

### CODE REVIEW

**Comment by tbugfinder** [comment]
```$$$$$$ Verifying the 'aws' system...

Profile: stack
Version: (not specified)
Target:  aws://

  ✔  stack: Test Suite: 'Stack'
     ✔  CloudFormation Stack stack-aws-quickstarter-test status is expected to eq "CREATE_COMPLETE" or eq "UPDATE_COMPLETE"
     ✔  S3 Bucket stack-aws-quickstarter-test-s3bucket-18kx0ja0t5wzt is expected to exist
     ✔  S3 Bucket stack-aws-quickstarter-test-s3bucket-18kx0ja0t5wzt is expected not to be public
     ✔  S3 Bucket stack-aws-quickstarter-test-s3bucket-18kx0ja0t5wzt is expected to have default encryption enabled
     ✔  S3 Bucket stack-aws-quickstarter-test-s3bucket-18kx0ja0t5wzt bucket_policy is expected to be empty
     ✔  S3 Bucket stack-aws-quickstarter-test-s3bucket-18kx0ja0t5wzt region is expected to eq "eu-west-1"
     ✔  Stack Testing is expected to be truthy


Profile: Amazon Web Services  Resource Pack (inspec-aws)
Version: 1.50.5
Target:  aws://

     No tests executed.

Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 7 successful, 0 failures, 0 skipped
$$$$$$ Finished verifying the 'aws' system.
$$$$$$ Finished verifying the systems.

```

**Review by metmajer — APPROVED** [review]
Super cool @tbugfinder 👍

**Comment by metmajer** [comment]
@tbugfinder please consider a squash-merge into a single commit

**Comment by metmajer** [comment]
@tbugfinder I have a bit of a hard time with these enterprisey input parameters. I sense a fundamental problem: the dynamic resource itself should be used for storing meta information, and not use massive tagging of Cloud resources.

**Review by metmajer — CHANGES_REQUESTED** [review]
Please remove enteprise-only relevant tags from an open source contribution.

**Comment by tbugfinder** [comment]
> Please remove enteprise-only relevant tags from an open source contribution.

Those additional tags were dropped from the PR. I think there should be some kind of a solution to merge an enterprise tagging approach into AWS Quickstarter. This could be either at deployment time of ODS overall or when the QS is cloned into a project repo.

**Comment by metmajer** [comment]
@tbugfinder why not use the `tags` variable we had in the stack framework to ingest arbitrary tags? Then, those tags would be stored in the `terraform.tfvars.*`.

**Comment by tbugfinder** [comment]
It wasn't implemented on stack level as described as the (random) id had to be incorporated. A `merge(var.tags,{"Environment"=var.meta_environment,"StackId = local.id"})` could be a combination although two key names are hardcoded. AFAIK reports do not use specific names of variables or outputs section, but `Jenkinsfile.template` uses the meta_environment.

At which step would an ODS integration add an enterprise tagging approach?

**Comment by metmajer** [comment]
> At which step would an ODS integration add an enterprise tagging approach?

We want to avoid to make the enterprise bleed into open source, and we need to be strict. If the Terraform module in the Quickstarter takes a variable `tags`, enterprise users can inject whatever they need. In other words, let's keep the AWS Quickstarter close to AWS and distant to corporate entity. If AWS doesn't know anything about an IT Tower, then the Quickstarter should neither.

**Comment by tbugfinder** [comment]
I agree on removal of pre defined tags which are not needed in all cases - one or the other might be left.
Should ODS Administration/Installation Guide include a note on integrating an tagging approach into this quickstarter comparable to an enterprise proxy configuration or should there be a page in the Quickstarter Documentation (seems to be missing) which elaborates customizations needed for a harmonized tagging approach?

**Comment by metmajer** [comment]
@tbugfinder yes, some sort of Quickstarter documentation would be great. I'd keep it simple and limited to documentation vs. a "proxy approach". As a starter, I suggest mentioning the `tags` argument in the `README.md`. @nichtraunzer is working on a corporate user guide which should also mention this ability. Thoughts?

**Review by nichtraunzer — APPROVED** [review]
**enterprisey** input parameters have been removed and can be managed individual via common-tags.tf

**Comment by metmajer** [comment]
@nichtraunzer @tbugfinder nice approach with the common_tags :)

**Review by metmajer — APPROVED** [review]

**Comment by metmajer** [comment]
@nichtraunzer @tbugfinder please squash and commit

**Pull request merged**
