### PR TITLE
updates java to version 17 and gradle to version 7.3 port to 4.x

### LINKED ISSUE #651: Use Java 17 (LTS) in maven jenkins-agent and spring boot quickstarter
Java 17 has been released a couple of months ago. Since it is an LTS version, it might make sense to use it. Currently we are at Java 11. 
Once we on it, we could also update gradle in the spring boot quickstarter, we are 3 major versions behind.

Any reason what would speak against it? Too early?

### PR DESCRIPTION
**Pull request by stitakis**
fixes #651 port 4.x

### CODE REVIEW

**Review by kuebler — APPROVED** [review]
LGTM! 🚀

**Comment by stitakis** [comment]
@kuebler fyi, in my last commit I've added the jacoco bufgix (refs #700 and #701) otherwise the end to test (ODS AMI build) fails.

**Comment by renedupont** [comment]
looks good so far,  just had a couple of notes

- Is there a specific reason why you have different gradle versions for the springboot qs and for the agent (and both are not the latest btw)?
- Spring Boot is meanwhile on 2.6.2 😆

**Review by renedupont — APPROVED** [review]

**Comment by stitakis** [comment]
@renedupont no special reason for the different versions of gradle... I'll create another PR to use the same version everywhere and also upgrade spring boot to the latest one.

**Comment by stitakis** [comment]
@renedupont feel free to submit a PR if you like to harmonize the gradle version and upgrade to latest spring boot

**Pull request merged**
