### PR TITLE
Add AWS Quickstarter for 3.x

### PR DESCRIPTION
**Pull request by nichtraunzer**
see #515

### CODE REVIEW

**Comment by braisvq1996** [comment]
Hi @metmajer , for this quickstarter it should be also necesary to update the Makefile in ods quickstarters and the Config map for the provisioning application in ods-core?

**Comment by metmajer** [comment]
Yes, @braisvq1996, we need to follow up here. Do you want to provide some guidance to @nichtraunzer ?

**Comment by borja44** [comment]
> Yes, @braisvq1996, we need to follow up here. Do you want to provide some guidance to @nichtraunzer ?

We're working on it

**Comment by michaelsauter** [comment]
> update the Makefile in ods quickstarters and the Config map for the provisioning application in ods-core

Good point! To add on this: note that during an upgrade of an existing ODS installation, the list of quickstarters in the prov app does NOT get updated automatically. This is on purpose, to allow each installation to list their own quickstarters. As a consequence, you'll need to manually edit the prov app properties to add this quickstarter to an existing installation.

**Pull request merged**
