### PR TITLE
WIP: Add gcc/g++ to support builds with CGO_ENABLED=1

### LINKED ISSUE #230: Add gcc/g++ to support builds with CGO_ENABLED=1
**Describe the bug**
Golang builds can either yield a static, fully self-contained binary, or be dynamically-linked against a C library. Currently, when building the latter using `CGO_ENABLED=1`, the build fails because of a missing `gcc`.

**To Reproduce**
`CGO_ENABLED=1 go build`

**Expected behavior**
The build succeeds.

**Affected version (please complete the following information):**
 - OpenShift: [e.g. 3.9, 3.11]
 - OpenDevStack 2.x

**Proposed solution**
Add `gcc` and `gcc-c++` into the Golang build slave. The presence of both further allows developers to import C/C++ files into Golang. For this to work, in the Dockerfile, add:

```
RUN yum install -y gcc gcc-c++
```

### PR DESCRIPTION
**Pull request by metmajer**
Closes #230

### CODE REVIEW

**Comment by metmajer** [comment]
Also adds `make` as it goes well with Go.

**Comment by metmajer** [comment]
@michaelsauter that would make most sense. Let me remove it from here again.

**Comment by michaelsauter** [comment]
@metmajer Perfect, please open an issue in ods-core to add it there.

**Comment by metmajer** [comment]
@michaelsauter cheers, will do soon

**Comment by michaelsauter** [comment]
@metmajer Do you want to merge this PR? As it is still labeled with `WIP`? Seems ready for me ...

**Comment by tbugfinder** [comment]
Does the gcc/g++ version matter? How would a user get to a later version if needed?

**Comment by michaelsauter** [comment]
@tbugfinder If a later version is needed, users would need to build their own slave (we should have a guide how to do that - it is not that difficult) or contribute a new version to ODS.

**Comment by metmajer** [comment]
@michaelsauter @clemensutschig so the open question here has been the following: making gcc and g++ available is one thing. The dependency of `CGO_ENABLED=1` on a C library is another one. The latter needs to exist in an ODS component that wants to make use of this feature. Otherwise, users run into a "file not found" error. I needed to test-drive the approach first in a Golang ODS component before coming to a conclusion, hence the `WIP`.

**Pull request merged**
