### PR TITLE
Fixing the Jenkins file to use proper way of creating Ionic project. …

### PR DESCRIPTION
**Pull request by bljubisic**
…Also, removed bunch of files which are not necessary anymore.

### CODE REVIEW

**Comment by bljubisic** [comment]
What I can see this failed: Error: unable to stream the build logs; caused by: unable to wait for build jenkins-slave-base-1 to run: timed out waiting for the condition

Why, I do not know.

**Comment by michaelsauter** [comment]
@bljubisic Nice work!

I assumed you have tested this locally?

The test failures are unrelated, they broke a while back - something in the way Github runs them has changed apparently and no-one had the time so far to look into it.

**Comment by bljubisic** [comment]
@michaelsauter I have tested locally and on Ubuntu container, so it should work. I would like for Manu to check it first before merging

**Comment by ManuelFeller** [comment]
@bljubisic Will check soon (throughout today) - right now on the react quickstarter...

**Comment by michaelsauter** [comment]
@bljubisic Sorry I wasn't very specific - with "locally" I meant in our cluster? You can try a branch of a quickstarter like this: https://github.com/opendevstack/ods-quickstarters/wiki/Run-quickstarter-via-Jenkins

**Comment by bljubisic** [comment]
I have added all changes needed for Jenkins to run quickstarter. This has been tested locally on our OpenShift.

**Comment by bljubisic** [comment]
I would have fiddled with sed but karma.conf.js is not created if you start blank app. That is why I am just copying the old one.

**Pull request merged**
