### PR TITLE
install python in nodejs12 agent

### LINKED ISSUE #742: ODS AMI build failing due missing python 3 in ionic quickstarter
ODS AMI build failing due an E2E test error of ionic quickstarter.

This is affecting branches `master` and `4.x`.

logs
```
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: + npm i -g @ionic/cli@6.13.1[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: npm WARN deprecated superagent@5.3.1: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: /home/jenkins/.npm-global/bin/ionic -> /home/jenkins/.npm-global/lib/node_modules/@ionic/cli/bin/ionic[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: + @ionic/cli@6.13.1[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: added 212 packages from 157 contributors in 14.259s[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: [Pipeline] sh[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: + npm install[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: npm WARN deprecated har-validator@5.1.5: this library is no longer supported[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs:[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: > nice-napi@1.0.2 install /tmp/workspace/unitt-cd/unitt-cd-run-unitt-fe-ionic-test-unitt-master/node_modules/nice-napi[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: > node-gyp-build[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs:[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python Python is not set from command line or npm configuration[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python Python is not set from environment variable PYTHON[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python checking if "python3" can be used[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python - "python3" is not in PATH or produced an error[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python checking if "python" can be used[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python - executable path is "/usr/bin/python"[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python - version is "2.7.5"[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python - version is 2.7.5 - should be >=3.6.0[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python **********************************************************[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python You need to install the latest version of Python.[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python Node-gyp should be able to find and use Python. If not,[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python you can try one of the following options:[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python   (accepted by both node-gyp and npm)[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python - Set the environment variable PYTHON[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python - Set the npm configuration variable python:[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python For more information consult the documentation at:[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python https://github.com/nodejs/node-gyp#installation[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python **********************************************************[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! find Python[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! configure error[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! stack Error: Could not find any Python installation to use[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! stack     at PythonFinder.fail (/tmp/workspace/unitt-cd/unitt-cd-run-unitt-fe-ionic-test-unitt-master/node_modules/node-gyp/lib/find-python.js:330:47)[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! stack     at PythonFinder.runChecks (/tmp/workspace/unitt-cd/unitt-cd-run-unitt-fe-ionic-test-unitt-master/node_modules/node-gyp/lib/find-python.js:159:21)[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! stack     at PythonFinder.<anonymous> (/tmp/workspace/unitt-cd/unitt-cd-run-unitt-fe-ionic-test-unitt-master/node_modules/node-gyp/lib/find-python.js:266:16)[0m
[2022-03-02T04:45:02.210Z] [0;32m    amazon-ebs: gyp ERR! stack     at PythonFinder.execFileCallback (/tmp/workspace/unitt-cd/unitt-cd-run-unitt-fe-ionic-test-unitt-master/node_modules/node-gyp/lib/find-python.js:297:7)[0m
```

### PR DESCRIPTION
**Pull request by stitakis**
fixes #742

### CODE REVIEW

**Comment by stitakis** [comment]
Hi @gerardcl @henrjk I added you as reviewer, it looks like ionic needs python version 3, could one of you please have a quick look if I added a proper way to install python?

**Review by bljubisic — APPROVED** [review]
Looks ok to me, but lets check with python guys :)

**Review by bljubisic — DISMISSED** [review]

**Comment by stitakis** [comment]
@clemensutschig this is the fix for the fe-ionic qs

**Review by bljubisic — APPROVED** [review]

**Comment by braisvq1996** [comment]
@stitakis, @bljubisic  is there any reason why python was added into Dockerfile.centos7 but not Dockerfile.ubi8 ?
Should we align both dockerfiles and install Python on them ?

**Pull request merged**
