### PR TITLE
#795 Removed node_module/cypress include as tslint complained; update…

### PR DESCRIPTION
**Pull request by herrkoch**
…d dependencies

Fixes https://github.com/opendevstack/ods-core/issues/795

Tasks: 
- [x] Updated documentation in `docs/modules/...` directory
- [ ] Adjusted and verified tests in `tests/...` directory

### CODE REVIEW

**Comment by clemensutschig** [comment]
@herrkoch  - you sure we want to lint tests? .. just saying :d

**Review by cschweikert — APPROVED** [review]

**Comment by clemensutschig** [comment]
@georgfedermann can you try if that works?

**Comment by georgfedermann** [comment]
@clemensutschig I see the same behaviour in the tests after cherry-picking this commit
quote from the logs:
````
    amazon-ebs: > e2e@0.0.0 lint /tmp/workspace/unitt-cd/unitt-cd-run-unitt-cypress-unitt-master
    amazon-ebs: > tslint --project .
    amazon-ebs:
    amazon-ebs: /tmp/workspace/unitt-cd/unitt-cd-run-unitt-cypress-unitt-master/node_modules/cypress/types/net-stubbing.ts:7:15
    amazon-ebs: ERROR: 7:15    semicolon           Missing semicolon
    amazon-ebs: ERROR: 8:39    semicolon           Missing semicolon
    amazon-ebs: ERROR: 9:16    semicolon           Missing semicolon
    amazon-ebs: ERROR: 10:20   semicolon           Missing semicolon
    amazon-ebs: ERROR: 11:25   semicolon           Missing semicolon
    amazon-ebs: ERROR: 17:4    semicolon           Missing semicolon
    amazon-ebs: ERROR: 23:59   unified-signatures  This overload and the one on line 29 can be combined into one signature with an optional parameter.
    amazon-ebs: ERROR: 24:33   unified-signatures  This overload and the one on line 29 can be combined into one signature with an optional parameter.
    amazon-ebs: ERROR: 25:10   unified-signatures  This overload and the one on line 29 can be combined into one signature with an optional parameter.
    amazon-ebs: ERROR: 33:5    member-ordering     Declaration of instance field not allowed after declaration of instance method. Instead, this should come at the beginning of the class/interface.
    amazon-ebs: ERROR: 37:5    member-ordering     Declaration of instance field not allowed after declaration of instance method. Instead, this should come at the beginning of the class/interface.
    amazon-ebs: ERROR: 38:4    semicolon           Missing semicolon
...
    amazon-ebs:     --- PASS: TestQuickstarter/be-fe-mono-repo-plain (268.74s)
    amazon-ebs:     --- PASS: TestQuickstarter/be-gateway-nginx (268.01s)
    amazon-ebs:     --- PASS: TestQuickstarter/be-golang-plain (306.67s)
    amazon-ebs:     --- PASS: TestQuickstarter/be-java-springboot (411.03s)
    amazon-ebs:     --- PASS: TestQuickstarter/be-python-flask (376.01s)
    amazon-ebs:     --- PASS: TestQuickstarter/be-scala-play (446.07s)
    amazon-ebs:     --- PASS: TestQuickstarter/be-typescript-express (411.00s)
    amazon-ebs:     --- PASS: TestQuickstarter/docker-plain (233.04s)
    amazon-ebs:     --- PASS: TestQuickstarter/ds-jupyter-notebook (373.09s)
    amazon-ebs:     --- PASS: TestQuickstarter/ds-ml-service (480.97s)
    amazon-ebs:     --- PASS: TestQuickstarter/ds-rshiny (1003.30s)
    amazon-ebs:     --- FAIL: TestQuickstarter/e2e-cypress (232.97s)
````

**Comment by clemensutschig** [comment]
@herrkoch  @cschweikert  - can you take a look? this does not seem to solve the problem! ...

**Comment by clemensutschig** [comment]
@georgfedermann  - did you push this up to your bitbucket locally? otherwise that change will not be picked up ...

**Comment by herrkoch** [comment]
Hmm really strange, the `node_modules` shouldn't be linted anymore with these changes. I also think the changes were not picked up and it seems I can't run these tests without being a cluster admin, so maybe @michaelsauter could you do a test run on our cluster? I'd anyhow recommend to merge this PR as it fixes an open issue.

**Comment by georgfedermann** [comment]
@herrkoch @clemensutschig I cherry-picked the commit into the feature/ods-devenv branch and ran ods box builds for this branch where I still found the issue. Recent builds broke because of a timeout in the ods-verify tests but I've fixed that and will double check.

**Comment by georgfedermann** [comment]
@herrkoch @clemensutschig After fixing the timeout issue I've run the tests again and they work out!
Apparently, the changes were actually not picked up in the previous test.

**Review by michaelsauter — APPROVED** [review]

**Pull request merged**
