### PR TITLE
change /tmp permissions in inf-terraform-agent

### PR DESCRIPTION
**Pull request by tbugfinder**
Fix permissions in /tmp to make ruby/bundler happy when installing Gems.
Bundler expects +t on /tmp.

### CODE REVIEW

**Comment by metmajer** [comment]
Thanks for the contribution @tbugfinder! Are you able to look into the error?

**Comment by metmajer** [comment]
@braisvq1996 can you check if @tbugfinder needs something?

**Review by braisvq1996 — DISMISSED** [review]
We can merge this PR and fix Nodejs 18 build in another one

**Review by braisvq1996 — APPROVED** [review]
Now that fix for nodejs18 is in place (and we needed to fix conflicts on changelog file) we can merge after test are successfully

**Pull request merged**
