### PR TITLE
update rust quickstarter MSRV and boilerplate refactor and docs

### PR DESCRIPTION
**Pull request by gerardcl**
In this update, part of a recurrent series of maintenance and improvements for the Rust Axum Quickstarter, we are:

- updating the MSRV to 1.79.0
- update CICD agent dependencies
- align use of `nextest` also with `llvm-cov` codegen (ensuring isolated process per test case run)
- refactor for better tracing/logging support with official `RUST_LOG` config
- enable better automated settings handling with `.env` files support
- enable temporal environment variables overwriting for test case runs

Tasks: 
- [x] Updated documentation in `docs/modules/...` directory
- [x] Ran tests in `<quickstarter>/testdata` directory

### CODE REVIEW

**Review by kuebler — APPROVED** [review]
LGTM! 🚀

**Comment by braisvq1996** [comment]
@gerardcl I wil use golden test tomorow to verify it still works and get bak to you

**Comment by braisvq1996** [comment]
tests  for the new Quickstarter version went though

**Comment by gerardcl** [comment]
@FLIGHTLAMA @braisvq1996 @kuebler  ready, do final check, and, maybe, approve! 👍

**Pull request merged**
