### PR TITLE
AWS Quickstarter: add AWS SAM/CDK

### PR DESCRIPTION
**Pull request by tbugfinder**
Integrate AWS SAM CLI and AWS CDK into terraform agent so that developer frameworks can be integrated into the toolchain.

Tasks: 
- [ ] Updated documentation in `docs/modules/...` directory
- [ ] Ran tests in `<quickstarter>/testdata` directory

### CODE REVIEW

**Review by michaelsauter — APPROVED** [review]

**Review by metmajer — APPROVED** [review]
Nice work @tbugfinder !

**Comment by tbugfinder** [comment]
This PR has two approvals. What's needed to get it merged finally?

**Comment by metmajer** [comment]
@tbugfinder squash and merge please

**Comment by tbugfinder** [comment]
I'm not authorized.

**Comment by nichtraunzer** [comment]
Merged - thanks @felipecruz91

**Pull request merged**
