### PR TITLE
Improve QS tests

### PR DESCRIPTION
**Pull request by michaelsauter**
* Use go-cmp/cmp to highlight difference betwee want/got
* Use repo name reflecting actual provisioning (project-component)
* Extract verification into methods
* Cleanup resources by selector
* Rename test to be easier to search for them in output
* Allow to run each quickstarter separately: `make QUICKSTARTER=be-golang-plain test`
* Minor changes to log output, checks, etc.
* Consistent bash scripts (`set -eu; set -o pipefail`, and use `curl -sS` everywhere)

### CODE REVIEW

**Comment by clemensutschig** [comment]
Cool. The reason we introduced Component id .. was because in some cases using the quickstarter Name as compoent name was too long for k8s... just fyi

**Comment by michaelsauter** [comment]
@clemensutschig I did not change anything regarding "component ID" really... I just extracted the repo name into a variable to easily reuse.

The other topic regarding cleanup: I have to look into this - we should find a way that both works on the first run and still fails on error. Otherwise it's just too flaky.

**Comment by clemensutschig** [comment]
@michaelsauter  - if I had one more wish :)

can you remove the --repository param requirement (https://github.com/opendevstack/ods-quickstarters/blob/task/improve-qs-tests/tests/scripts/setup_bitbucket_test_project.sh#L73-L76) .. and just return if no repo is passed after creating the bitbucket project - that way - we can call this script out of quickstarter-test.sh (https://github.com/opendevstack/ods-quickstarters/blob/task/improve-qs-tests/tests/quickstarter-test.sh#L24)- to just create the bb test project (and prevent odd concurrency issues we are seeing in 1/5 builds) (@georgfedermann  fyi)

**Comment by michaelsauter** [comment]
@clemensutschig I will look into that.

**Comment by michaelsauter** [comment]
Successful tests (running them one-by-one now):

- [ ] be-fe-mono-repo-plain
- [ ] be-gateway-nginx
- [ ] be-golang-plain
- [ ] be-java-springboot
- [ ] be-python-flask
- [ ] be-scala-play
- [ ] be-typescript-express
- [ ] docker-plain
- [ ] ds-jupyter-notebook
- [ ] ds-ml-service
- [ ] ds-rshiny
- [ ] e2e-cypress
- [ ] e2e-spock-geb
- [ ] fe-angular
- [ ] fe-ionic
- [ ] ods-document-gen-svc
- [ ] ods-provisioning-app
- [ ] release-manager

**Comment by michaelsauter** [comment]
@clemensutschig Pod check is fixed now and Bitbucket project is setup early on once (https://github.com/opendevstack/ods-quickstarters/pull/437/commits/ed12191edfaea0ceea4a4ab1b50ce876d28d5fa2).

**Comment by michaelsauter** [comment]
@renedupont @clemensutschig @georgfedermann All tests passed now (run individually). Please approve :)

**Pull request merged**
