### PR TITLE
master: change external url for repo and e2e quickstarter tests update to latest version

### PR DESCRIPTION
**Pull request by s2oBCN**
Fix error because of change in external url

### CODE REVIEW

**Review by clemensutschig — DISMISSED** [review]

**Comment by clemensutschig** [comment]
terraform is still failing?

**Comment by clemensutschig** [comment]
can you pullin @gerardcl  and really solve this once and for all?

**Comment by s2oBCN** [comment]
> terraform is still failing?

They changed the urls today https://dl.fedoraproject.org/pub/epel
I updated with the new ones

**Comment by clemensutschig** [comment]
I am surprised the spock one is working ... :( seriously - it's using the same urls...

**Comment by clemensutschig** [comment]
@s2oBCN - the URL is working again?
https://www.w3schools.com/html/tryit.asp?filename=tryhtml_basic_paragraphs

the only thing that changed is v3.7 now ...

**Comment by s2oBCN** [comment]
> I am surprised the spock one is working ... :( seriously - it's using the same urls...

Finally working! :)
3 external urls changed in one day!

**Review by clemensutschig — APPROVED** [review]

**Review by clemensutschig — APPROVED** [review]

**Pull request merged**
