### PR TITLE
fix terraform agents from jenkins agent base repo changes.

### LINKED ISSUE #724: terraform agent build failing
**Describe the bug**
Due to recent changes/removals from centos repos terraform agent fails on building.

**To Reproduce**
1. Go to ['this github action run from 4.x'](https://github.com/opendevstack/ods-quickstarters/runs/5244440597?check_suite_focus=true)
2. See error

**Expected behavior**
Should build with success

**Screenshots**

**Affected version (please complete the following information):**
 - OpenShift: 4
 - OpenDevStack master

### PR DESCRIPTION
**Pull request by tbugfinder**
fix terraform agents from jenkins agent base repo changes.

Closes #724
Fixes #724

Tasks: 
- [ ] Updated documentation in `docs/modules/...` directory
- [ ] Ran tests in `<quickstarter>/testdata` directory

### CODE REVIEW

**Comment by tbugfinder** [comment]
Is a review not required on 4.x branch by intention?

**Review by gerardcl — APPROVED** [review]
LGTM! 🚀 

what about master?

**Comment by gerardcl** [comment]
> Is a review not required on 4.x branch by intention?

it is required IMHO but not sure if we can force it

**Comment by tbugfinder** [comment]
> > Is a review not required on 4.x branch by intention?
> 
> 
> 
> it is required IMHO but not sure if we can force it

There's a guide (I cannot apply it 😇)

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

**Comment by gerardcl** [comment]
Hi @tbugfinder @michaelsauter @metmajer I've just applied the following branch matching protection with same protection as master has (such pattern protects any main release branches existing and to exist):
Screenshot 2022-02-22 at 08 10 47

If you like it we could apply same patter to other repos we need it.

**Pull request merged**
