### PR TITLE
Add missing imports to Spock/Geb Quickstarter

### LINKED ISSUE #492: e2e-spock-geb compilation error in GebConfig.groovy
**Describe the bug**
The quickstarter-generated pipeline fails with a compilation error in GebConfig.groovy.

**To Reproduce**
1. Provision an EDP project
2. Provision a e2e-spock-geb component
3. The ods-qs-demo-app-end-to-end-3x job completes correctly.
4. The demo-app-end-to-end-master job shows a compilation error in GebConfig.groovy and finishes as unstable.

**Expected behavior**
GebConfig.groovy compiles correctly and the job finishes succesfully

**Screenshots**
image

**Affected version (please complete the following information):**
 - OpenShift: OKD version:
OpenShift Master: unknown
Kubernetes Master: v1.11.0+d4cacc0
OpenShift Web Console: v3.11.0+ea42280

 - OpenDevStack 3.x

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
> Task :installation-groovy
Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/jenkins/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.5.6/6936e700f0fb1b50bac0698ada4347a769d40199/groovy-2.5.6.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

[0K[1mDemoInstallation[m

[0K[1m  Test [22mclassMethod[31m FAILED[31m

  geb.error.UnableToLoadException: Unable to load configuration @ 'file:/tmp/workspace/t2-cd/t2-cd-demo-app-end-to-end-master/build/resources/installation/GebConfig.groovy' (with environment: )

  Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  script1605776752050542709543.groovy: 11: unable to resolve class WebClient 
   @ line 11, column 7.
           @Override
           ^
  
  script1605776752050542709543.groovy: 13: unable to resolve class WebClient 
   @ line 13, column 21.
               WebClient webClient = super.newWebClient(version);
                         ^
  
  2 errors

[m

[0K[1;31mFAILURE: [39mExecuted 1 tests in 5s (1 failed)[m


1 test completed, 1 failed
There were failing tests. See the report at: file:///tmp/workspace/t2-cd/t2-cd-demo-app-end-to-end-master/build/reports/tests/installation-groovy/index.html
```

**Additional context**
It cannot find some classes. Apparently it lacks the needed imports.

### PR DESCRIPTION
**Pull request by jafarre-viewnext**
Added missing imports in GebConfig.groovy so that this code compiles correctly.
Tested in an edp box.

Closes #492 
Fixes #492 

Tasks: 
- [ ] Updated documentation in `docs/modules/...` directory
- [ ] Ran tests in `<quickstarter>/testdata` directory

### CODE REVIEW

**Review by clemensutschig — APPROVED** [review]

**Comment by clemensutschig** [comment]
sorry @jafarre-viewnext

**Review by metmajer — APPROVED** [review]
Thanks @jafarre-viewnext!

**Review by clemensutschig — DISMISSED** [review]

**Comment by jafarre-viewnext** [comment]
I realised I had added two unneeded imports. I removed them and retested.

**Comment by metmajer** [comment]
@jafarre-viewnext please squash and merge this commit and make sure it contains the title of this PR as its commit message (good practice) 👍

**Comment by jafarre-viewnext** [comment]
> @jafarre-viewnext please squash and merge this commit and make sure it contains the title of this PR as its commit message (good practice) 👍

Done

**Review by clemensutschig — APPROVED** [review]

**Comment by metmajer** [comment]
@jafarre-viewnext please also do a `git cherry-pick $sha` into the `3.x` branch to make it appear on our upcoming ODS 3.1 release. Let me know if you need help.

**Comment by jafarre-viewnext** [comment]
@metmajer Done

**Pull request merged**
