### PR TITLE
Remove filter which disables all non centos 8 repos.

### PR DESCRIPTION
**Pull request by nichtraunzer**
As requested by Felipe:
This fix removes the filter which disables all non centos 8 repos. 

The argument does not find any repos which matches the filter therefore it fails with exit 1.

Tasks: 
- [ ] Updated documentation in `docs/modules/...` directory
- [ ] Ran tests in `<quickstarter>/testdata` directory

### CODE REVIEW

**Comment by felipecruz91** [comment]
The image now builds successfully in an OCP 4 cluster. Thank you for your prompt action @nichtraunzer.

Would you add a new entry in the CHANGELOG.md so we can merge it to master?

**Comment by tbugfinder** [comment]
Why do we have all those different repos in the base image?
```
repo id                                 repo name
centos-appstream                        CentOS-8-AppStream
centos-baseos                           CentOS-8-BaseOS
localdev-openstack-16-for-rhel-8-rpms   localdev-openstack-16-for-rhel-8-rpms
localdev-rhel-8-appstream-rpms          localdev-rhel-8-appstream-rpms
localdev-rhel-8-baseos-rpms             localdev-rhel-8-baseos-rpms
localdev-rhel-8-codeready-builder-rpms  localdev-rhel-8-codeready-builder-rpms
localdev-rhel-8-fast-datapath-rpms      localdev-rhel-8-fast-datapath-rpms
localdev-rhel-8-rt-rpms                 localdev-rhel-8-rt-rpms
localdev-rhel-8-server-ansible-2.9-rpms localdev-rhel-8-server-ansible-2.9-rpms
localdev-rhel-8-server-ose-rpms         localdev-rhel-8-server-ose-rpms
openstack-16-for-rhel-8-rpms            openstack-16-for-rhel-8-rpms
rhel-8-advanced-virt                    rhel-8-advanced-virt
rhel-8-ansible-2.9                      rhel-8-ansible-2.9
rhel-8-appstream                        rhel-8-appstream
rhel-8-baseos                           rhel-8-baseos
rhel-8-codeready-builder-rpms           rhel-8-codeready-builder-rpms
rhel-8-fast-datapath                    rhel-8-fast-datapath
rhel-8-fast-datapath-aarch64            rhel-8-fast-datapath-aarch64
rhel-8-nfv                              rhel-8-nfv
rhel-8-server-ose                       rhel-8-server-ose

```

**Review by clemensutschig — DISMISSED** [review]

**Comment by metmajer** [comment]
@nichtraunzer @felipecruz91 @michaelsauter please see to closing this one, cheers!

**Comment by metmajer** [comment]
Cheers!

**Pull request merged**
