### PR TITLE
Add release-manager.yml to each quickstarter

### LINKED ISSUE #53: add '.pipeline-config.yml' to root of each project quickstarter
**Is your feature request related to a problem? Please describe.**
No, MRO enhancement

**Describe the solution you'd like**
add a file called '.pipeline-config.yml' to each project quickstarter

**Describe alternatives you've considered**
none, needed.

**Additional context**
leave for now empty ...

### PR DESCRIPTION
**Pull request by michaelsauter**
Closes #53.

### CODE REVIEW

**Comment by fadivr** [comment]
we would need the following addtional informations in the yml file:
Name of    Software | Supplier | Version | Description of Functionality | References

**Comment by michaelsauter** [comment]
@fadivr Can you please open a new issue with this, explaining the rationale? And @metmajer could you please comment if we need this for v2, and how it should look like then? Thanks.

**Comment by fadivr** [comment]
add feature request #75 for storing data for generation of DSD document

**Comment by metmajer** [comment]
@michaelsauter I'll discuss the needs for this with @fadivr, as I need to get a clearer picture about the why

**Pull request merged**
