### PR TITLE
Master branch detection for production builds in Angular

### PR DESCRIPTION
**Pull request by ManuelFeller**
Adding production build detection from ionic quickstarter to the angular quickstarter, solving issue #18

### CODE REVIEW

**Comment by cschweikert** [comment]
@ManuelFeller Mh, I guess this change is not necessary: the prod flag is always attached from within the ``package.json``. See also https://github.com/opendevstack/ods-quickstarters/blob/master/fe-angular/files/package.json. Maybe it also failes now on master since it will attach ``--prod`` twice?

**Comment by cschweikert** [comment]
In addition I would suggest to always build as production build. I had cases in the past, where certain unwanted behavior only occured due to the production build, e.g. caused by the uglification.

**Comment by ManuelFeller** [comment]
I get the point @cschweikert, and I can remove that again (was somehow unaware of that change; I think when I opened that issue this was not integrated in the `package.json` - and I forgot to check there since I normally do not put the production flag in the `package.json` - a habit from Ionic projects).

Maybe you can add your points here a bit more detailed (performance judging, minification and E2E issues you experienced) and then @bljubisic, @netzartist, @rianet, @m-apsolon, @herrkoch, @akhilsoman and @ultrasonicsoft can let us know if they see it the same way or if they want to have dev builds for a reason.

**Comment by cschweikert** [comment]
As @ManuelFeller mentioned there are pros and cons when deferring between dev and prod build.
Pros:
 * faster builds in dev mode
 * source maps/better readable code in the hosted application, that was build in dev mode
Cons:
 * final performance from code optimization can only be experienced in the prod version on master
 * dev and prod builds are not identical. This will increase the risk of issues that will only appear in a production build from master.

Example: I once did the mistake and relied on the name property of a class, which was turned into a random letter due to uglification 😅

I would suggest to start with production builds from all branches to not be surprised by any branch-specific build behavior. If someone needs special treatment for dev branches, e.g. source maps, ``angular.json`` offers the possibility to create multiple build configurations with many different things to configure (uglification, source maps, budgets, etc.). Setting up something branch-specific would then be the respective developer's responsibility.

An alternative to this could be to call the production build with the additional parameter ``--sourceMap=true``. Less invasive, but with the greatest benefit of the dev build from above.

What do you think? :)

**Comment by ManuelFeller** [comment]
I would then go with prod builds and sourceMap=true.

This will also make sure that you run into resource issues with your build pod early (I had the case that dev worked but prod consumed quite a bit more and thus always broke because the pod ran out of memory).
In case we decide for this way I will recommendations / reasons from this thread to the `readme.md` of the generated project...

**Pull request merged**
