### PR TITLE
Update ionic to version 5 #21

### PR DESCRIPTION
**Pull request by bljubisic**
Fixing the Angular version used in Ionic quickstarter.

### CODE REVIEW

**Comment by bljubisic** [comment]
Yes, with Manu and Janet. We created a video for documentation for all FEs :)

**Comment by michaelsauter** [comment]
@bljubisic Nice. What would be the best way to make this available? Maybe you can upload it e.g. on YouTube and link it from the docs somewhere?

**Comment by ManuelFeller** [comment]
Regarding publishing the Video: we plan do collect feedback internally - and then (once we have blurred out the URL's that are for internal use only) upload it maybe. We could create an OpenDevStack Video Channel or use the Members personal ones... What do you prefer @michaelsauter ?

**Comment by michaelsauter** [comment]
@ManuelFeller official one would be cool - get in touch with @rattermeyer if there is already one.

**Pull request merged**
