### PR TITLE
fix nodejs12 chrome repo with http

### LINKED ISSUE #642: nodejs 12 jenkins agent build failing on ODS 4.x
**Describe the bug**
Looks like due to not defining the https://github.com/opendevstack/ods-quickstarters/blob/ca1faff5f01b454fdc47580512407bb2ab4fbce7/common/jenkins-agents/nodejs12/docker/yum.repos.d/google-chrome.repo#L3 as `https`, and no redirect handler, looks like that is the root cause of the issue we have (see logs below). If one targets the repos with `https` the packages are found.

**To Reproduce**
1. Within an ODS 4.x installation go an build latest 4.x nodejs12 jenkins agent
2. The build fail as per logs shared below

**Expected behavior**
The build of all the agents must work

**Affected version (please complete the following information):**
 - OpenShift: 4.x (and I bet also 3.x)
 - OpenDevStack 4.x, master (also 3.x?)

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
Downloading Packages:
(1/11): liberation-fonts-common-2.00.3-7.el8.no 193 kB/s |  25 kB     00:00
(2/11): liberation-fonts-2.00.3-7.el8.noarch.rp 147 kB/s |  20 kB     00:00
(3/11): liberation-mono-fonts-2.00.3-7.el8.noar 1.8 MB/s | 505 kB     00:00
(4/11): liberation-sans-fonts-2.00.3-7.el8.noar 3.7 MB/s | 610 kB     00:00
(5/11): liberation-serif-fonts-2.00.3-7.el8.noa 3.6 MB/s | 609 kB     00:00
(6/11): desktop-file-utils-0.23-8.el8.x86_64.rp 2.0 MB/s |  80 kB     00:00
(7/11): xdg-utils-1.1.2-5.el8.noarch.rpm        1.8 MB/s |  84 kB     00:00
(8/11): vulkan-loader-1.2.182.0-1.el8_4.x86_64. 1.8 MB/s | 120 kB     00:00
(9/11): mesa-vulkan-drivers-20.3.3-2.el8.x86_64  29 MB/s | 5.4 MB     00:00
[MIRROR] google-chrome-stable-93.0.4577.63-1.x86_64.rpm: Status code: 404 for http://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome-stable-93.0.4577.63-1.x86_64.rpm (IP: 74.125.193.136)
[MIRROR] google-chrome-stable-93.0.4577.63-1.x86_64.rpm: Status code: 404 for http://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome-stable-93.0.4577.63-1.x86_64.rpm (IP: 74.125.193.136)
[MIRROR] google-chrome-stable-93.0.4577.63-1.x86_64.rpm: Status code: 404 for http://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome-stable-93.0.4577.63-1.x86_64.rpm (IP: 74.125.193.136)
[MIRROR] google-chrome-stable-93.0.4577.63-1.x86_64.rpm: Status code: 404 for http://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome-stable-93.0.4577.63-1.x86_64.rpm (IP: 74.125.193.136)
[FAILED] google-chrome-stable-93.0.4577.63-1.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: Error downloading packages:
  Cannot download google-chrome-stable-93.0.4577.63-1.x86_64.rpm: All mirrors were tried
error: build error: error building at STEP "RUN yum repolist     && yum install -y --enablerepo centos-baseos,centos-appstream xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib     && yum install -y --enablerepo centos-baseos,centos-appstream,google-chrome google-chrome-stable     && yum clean all -y": error while running runtime: exit status 1
```

**Additional context**
I believe we need to keep updating any requests from `http` to `https`.

### PR DESCRIPTION
**Pull request by gerardcl**
Fixes #642 

Tasks: 
- [x] Updated documentation in `docs/modules/...` directory
- [x] Ran tests in `<quickstarter>/testdata` directory

### CODE REVIEW

**Comment by gerardcl** [comment]
will provide later today fixes for master and 3.x

**Comment by metmajer** [comment]
@gerardcl we'll not do any 3.x installations anymore, so you could skip the merge to 3.x

**Comment by felipecruz91** [comment]
@gerardcl out of curiosity, why the `http` has started to fail now? Looking at the history of the `google-chrome.repo` file, it's being like that since Nov 2020.

**Comment by gerardcl** [comment]
@felipecruz91  I believe it is due to activities enforcing `https` all around and/or some changes on the rpm that do not follow redirects anymore? maybe could even be a cluster-level enforcement...

**Pull request merged**
