### PR TITLE
add gateway kong quickstarter

### PR DESCRIPTION
**Pull request by stefanlack**
Adds gateway kong quickstarter.

The quickstarter was initially created by @tjaeschke and was migrated to ODS 2.0 by me.

### CODE REVIEW

**Comment by michaelsauter** [comment]
Cool.

Could you:
- Adjust this (especially the `Jenkinsfile` so that it fits with `master`? See the 3.x docs as well for guidance.
- Explain how I would use this as a user?
- Give some hints how this would compare to the Nginx based quickstarter and what the advantages of Kong are?
- Let us know whether you plan to maintain this long-term?

Cheers!

**Comment by stefanlack** [comment]
I am currently working on an initial documentation, that I will add to this PR.

**Comment by stefanlack** [comment]
Unfortunately, we do not have an OpenDevStack 3 running on our site and we do not see when (and if) we are going to migrate to the 3.0 branch in the near future (due to the covid-19 implications). 

Therefore, I am sorry to say that I am not able to migrate the quickstarter right now .

**Comment by stefanlack** [comment]
Not sure if we should keep this PR open, so that someone else (who maybe need this type of quickstarter) can do the migration to the 3.0 branch? I think I will wait a week, before finally closing this.

**Comment by michaelsauter** [comment]
@stefanlack Thanks for the update. Let's just keep it open I think. Maybe we can mark it as Draft/WIP?

**Comment by tbugfinder** [comment]
should this PR be prefixed with WIP: or closed?

**Comment by stefanlack** [comment]
I will close this PR, since I no longer work on open dev stack and the pr is pretty old now.

**Pull request closed without merging**
